export interface Member {
  id: string
  firstName: string
  lastName: string
  email: string
  phone: string
  company: string
  businessCategory: string
  serviceDescription: string
  tradeOrBusinessType: string // Keep for backwards compatibility
  role: string
  location: string
  membershipType: string
  status: "active" | "paused" | "inactive"
  joinDate: string
  renewalDate: string
  eventsAttended: number
  tags: string[]
  notes: string
  website?: string
}

export interface Event {
  id: string
  title: string
  date: string
  location: string
  description: string
  attendeeIds: string[]
}

const STORAGE_KEYS = {
  MEMBERS: "tartan_talks_members",
  EVENTS: "tartan_talks_events",
}

const DEMO_MEMBERS: Member[] = [
  {
    id: "2",
    firstName: "Connor",
    lastName: "Wright",
    email: "connor@tartantimber.com",
    phone: "07565508006",
    company: "Tartan Talks Ltd",
    businessCategory: "Other Services",
    serviceDescription: "Technology & Operations",
    tradeOrBusinessType: "Technology & Operations",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["technology", "operations"],
    notes: "",
  },
  {
    id: "3",
    firstName: "Mark",
    lastName: "Innes",
    email: "mark@tartantimber.com",
    phone: "07769677121",
    company: "Tartan Talks Ltd",
    businessCategory: "Other Services",
    serviceDescription: "Timber supplier, Business networking host.",
    tradeOrBusinessType: "Timber supplier, Business networking host.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["timber", "networking"],
    notes: "",
  },
  {
    id: "4",
    firstName: "Ashley",
    lastName: "O'Neill",
    email: "ashley@tartantimber.com",
    phone: "07768244396",
    company: "Tartan Talks Ltd",
    businessCategory: "Other Services",
    serviceDescription: "Timber supplier, Business networking host.",
    tradeOrBusinessType: "Timber supplier, Business networking host.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["timber", "networking"],
    notes: "",
  },
  {
    id: "5",
    firstName: "Adam",
    lastName: "Kelly",
    email: "akelly_bls@outlook.com",
    phone: "07817967877",
    company: "A Kelly Stonework",
    businessCategory: "Construction & Building",
    serviceDescription:
      "All aspects of building work, stone, brick, block, lime pointing, structural alterations and hard landscaping.",
    tradeOrBusinessType:
      "All aspects of building work, stone, brick, block, lime pointing, structural alterations and hard landscaping.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["building", "stonework", "landscaping"],
    notes: "",
  },
  {
    id: "6",
    firstName: "Alasdair",
    lastName: "Dunse",
    email: "alasdair@dunsepowercleaning.com",
    phone: "07443639667",
    company: "Dunse power cleaning",
    businessCategory: "Property, Cleaning & Maintenance",
    serviceDescription: "Commercial & residential external cleaning.",
    tradeOrBusinessType: "Commercial & residential external cleaning.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["cleaning"],
    notes: "",
  },
  {
    id: "7",
    firstName: "Alastair",
    lastName: "Elliott",
    email: "a.elliott@cleaningdoctor.co.uk",
    phone: "07738244485",
    company: "Cleaning Doctor Edinburgh",
    businessCategory: "Property, Cleaning & Maintenance",
    serviceDescription: "Carpet and upholstery cleaning.",
    tradeOrBusinessType: "Carpet and upholstery cleaning.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["cleaning", "carpet"],
    notes: "",
  },
  {
    id: "8",
    firstName: "Allan",
    lastName: "Cornet",
    email: "allan@acwelectrical.com",
    phone: "07985603879",
    company: "ACW Electrical & Solar Ltd & Tenroc Investments Ltd",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription:
      "Domestic electrical services, solar PV and battery storage installation. Also involved in property investment",
    tradeOrBusinessType:
      "Domestic electrical services, solar PV and battery storage installation. Also involved in property investment",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical", "solar", "property"],
    notes: "",
  },
  {
    id: "9",
    firstName: "Alun",
    lastName: "Joseph",
    email: "alun@dtpsouthfield.co.uk",
    phone: "01316571001",
    company: "DTP Southfield",
    businessCategory: "Other Services",
    serviceDescription:
      "Printing, flyers, business cards, brochures, banners etc Workwear, full supply of embroidered& printed garments.",
    tradeOrBusinessType:
      "Printing, flyers, business cards, brochures, banners etc Workwear, full supply of embroidered& printed garments.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["printing", "workwear"],
    notes: "",
  },
  {
    id: "10",
    firstName: "Andrew",
    lastName: "Graham",
    email: "info@tailoreddigitalsystems.com",
    phone: "07500822264",
    company: "Tailored Digital Systems Ltd",
    businessCategory: "Construction & Building",
    serviceDescription:
      "AI Automation for business owners looking to get their time back while continuing to grow. We build the infrastructures",
    tradeOrBusinessType:
      "AI Automation for business owners looking to get their time back while continuing to grow. We build the infrastructures",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["ai", "automation", "technology"],
    notes: "",
  },
  {
    id: "11",
    firstName: "Andrew",
    lastName: "Jack",
    email: "a.jack@target-comms.co.uk",
    phone: "07516147735",
    company: "Target Communications",
    businessCategory: "Technology & Digital",
    serviceDescription: "Telecoms, IT, devices, printers, doc management, CCTV, security, utilities.",
    tradeOrBusinessType: "Telecoms, IT, devices, printers, doc management, CCTV, security, utilities.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["telecoms", "it", "security"],
    notes: "",
  },
  {
    id: "12",
    firstName: "Andrew",
    lastName: "Laister",
    email: "laisterconstruction@outlook.com",
    phone: "07526235833",
    company: "Laister Construction ",
    businessCategory: "Construction & Building",
    serviceDescription: "Joinery/concruction principle contractor",
    tradeOrBusinessType: "Joinery/concruction principle contractor",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery", "construction"],
    notes: "",
  },
  {
    id: "13",
    firstName: "Andy",
    lastName: "McCardle",
    email: "Andrew.mccardle@uw.partners",
    phone: "07554900660",
    company: "Utility Warehouse",
    businessCategory: "Other Services",
    serviceDescription: "Utilities/Income Opportunity",
    tradeOrBusinessType: "Utilities/Income Opportunity",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["utilities"],
    notes: "",
  },
  {
    id: "14",
    firstName: "Callum",
    lastName: "Porteous",
    email: "callum@candgdevelopment.co.uk",
    phone: "07557335976",
    company: "C&G Developments Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "New builds, extensions,renovations, commercial works & project management.",
    tradeOrBusinessType: "New builds, extensions,renovations, commercial works & project management.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction", "development"],
    notes: "",
  },
  {
    id: "15",
    firstName: "Charlie",
    lastName: "Johnstone",
    email: "cjsignman@aol.com",
    phone: "07518350780",
    company: "Signman",
    businessCategory: "Technology & Digital",
    serviceDescription: "Graphic design, web design, signage, print, stationary, banners, vehicle wrap.",
    tradeOrBusinessType: "Graphic design, web design, signage, print, stationary, banners, vehicle wrap.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["design", "signage", "print"],
    notes: "",
  },
  {
    id: "16",
    firstName: "Chris",
    lastName: "Dodds ",
    email: "Chris@ctdscotland.com ",
    phone: "07743219750",
    company: "CTD Scotland Ltd ",
    businessCategory: "Construction & Building",
    serviceDescription: "Commercial fitout contractor - offices, bars, restaurants, hotels, shops. ",
    tradeOrBusinessType: "Commercial fitout contractor - offices, bars, restaurants, hotels, shops. ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["fitout", "commercial"],
    notes: "",
  },
  {
    id: "17",
    firstName: "Chris",
    lastName: "Jackson",
    email: "thecompleteheatingco@outlook.com",
    phone: "07876332968",
    company: "The Complete Heating Company",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All aspects of plumbing, heating and air source",
    tradeOrBusinessType: "All aspects of plumbing, heating and air source",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["plumbing", "heating"],
    notes: "",
  },
  {
    id: "18",
    firstName: "Chris",
    lastName: "Law",
    email: "chrislawroofing39@gmail.com",
    phone: "07791308254",
    company: "Law Roofing",
    businessCategory: "Construction & Building",
    serviceDescription: "All aspects of roofing, harling, guttering, chimney works & general building.",
    tradeOrBusinessType: "All aspects of roofing, harling, guttering, chimney works & general building.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["roofing", "building"],
    notes: "",
  },
  {
    id: "19",
    firstName: "Chris",
    lastName: "Lawson",
    email: "chris@lawsonjoinery.co.uk",
    phone: "07703004136",
    company: "The Fencing Specialist ",
    businessCategory: "Construction & Building",
    serviceDescription: "All aspects of joinery, kitchens & bathrooms, decking & fencing.",
    tradeOrBusinessType: "All aspects of joinery, kitchens & bathrooms, decking & fencing.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery", "fencing", "kitchens"],
    notes: "",
  },
  {
    id: "20",
    firstName: "Colin",
    lastName: "Dolby",
    email: "Colin@dimension-accounting.co.uk",
    phone: "07851687417",
    company: "Dimension Accounting ltd",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Accounting - Everything you'd expect plus advisory for your present and future. Your inhouse finance team without the employment headaches",
    tradeOrBusinessType:
      "Accounting - Everything you'd expect plus advisory for your present and future. Your inhouse finance team without the employment headaches",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["accounting", "finance"],
    notes: "",
  },
  {
    id: "21",
    firstName: "Craig",
    lastName: "Mcmahon",
    email: "Info@d4decor.co.uk",
    phone: "",
    company: "D4 Decor",
    businessCategory: "Construction & Building",
    serviceDescription: "Aimes taping  painting and decorating ",
    tradeOrBusinessType: "Aimes taping  painting and decorating ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["decorating", "painting"],
    notes: "",
  },
  {
    id: "22",
    firstName: "Dan",
    lastName: "Renton",
    email: "",
    phone: "",
    company: "MomentumNRG Health & Wealth Management",
    businessCategory: "Health & Wellbeing",
    serviceDescription: "Weight management, property investment.",
    tradeOrBusinessType: "Weight management, property investment.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["health", "property"],
    notes: "",
  },
  {
    id: "23",
    firstName: "David",
    lastName: "Jardine",
    email: "daviejardine@outlook.com",
    phone: "07971959223",
    company: "Construction Management Consultant",
    businessCategory: "Construction & Building",
    serviceDescription: "Construction consultancy.",
    tradeOrBusinessType: "Construction consultancy.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction", "consultancy"],
    notes: "",
  },
  {
    id: "24",
    firstName: "David",
    lastName: "Todd",
    email: "davidtodd@kwuk.com",
    phone: "07723042477",
    company: "David Todd Sales & Lettings",
    businessCategory: "Estate Agency & Property Services",
    serviceDescription:
      "Provider of all estate agency & letting services, both residential, commercial & land. Advise on investors, landlords, companies & individuals.",
    tradeOrBusinessType:
      "Provider of all estate agency & letting services, both residential, commercial & land. Advise on investors, landlords, companies & individuals.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["estate-agency", "lettings"],
    notes: "",
  },
  {
    id: "25",
    firstName: "Dean",
    lastName: "Ivinson",
    email: "enquiries@ravelstonhouse.co.uk",
    phone: "07852912205",
    company: "Ravelston House Hotel",
    businessCategory: "Hospitality & Events",
    serviceDescription: "Bar, restaurant, meetings, events, accomodation, beer garden.",
    tradeOrBusinessType: "Bar, restaurant, meetings, events, accomodation, beer garden.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["hospitality", "hotel", "events"],
    notes: "",
  },
  {
    id: "26",
    firstName: "Dean",
    lastName: "Phillips",
    email: "dean@macintoshlfs.co.uk",
    phone: "07858475484",
    company: "Macintosh LFS",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Life insurance, mortgage protection,health insurance, house hold & contents, business insurance, shareholder protection, death in service, indemnity, liability, vans, tools, cargo & so much more.",
    tradeOrBusinessType:
      "Life insurance, mortgage protection,health insurance, house hold & contents, business insurance, shareholder protection, death in service, indemnity, liability, vans, tools, cargo & so much more.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["insurance", "financial-services"],
    notes: "",
  },
  {
    id: "27",
    firstName: "Dean",
    lastName: "Thomson",
    email: "",
    phone: "",
    company: "The Lending Channel",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Specialist finance broker, local investors, funding for commercial & residential property, premesis, land, cash flow, business growth.",
    tradeOrBusinessType:
      "Specialist finance broker, local investors, funding for commercial & residential property, premesis, land, cash flow, business growth.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["finance", "property"],
    notes: "",
  },
  {
    id: "28",
    firstName: "Derek",
    lastName: "Welsh",
    email: "Thegargeconvertonco@gmail.com",
    phone: "07494582524",
    company: "The Garage Conversion Company",
    businessCategory: "Construction & Building",
    serviceDescription: "Specialise in garage conversion",
    tradeOrBusinessType: "Specialise in garage conversion",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction", "conversion"],
    notes: "",
  },
  {
    id: "29",
    firstName: "Donna",
    lastName: "Kerr/ Kuran Olak",
    email: "donna@dmkfinance.co.uk",
    phone: "07915484732/ 07956300620",
    company: "DMK Finance",
    businessCategory: "Finance & Legal",
    serviceDescription: "Business & commercial property loans, asset & invoice finance.",
    tradeOrBusinessType: "Business & commercial property loans, asset & invoice finance.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["finance", "property"],
    notes: "",
  },
  {
    id: "30",
    firstName: "Dougie",
    lastName: "Grant",
    email: "douggrantplumbing@gmail.com",
    phone: "07885754004",
    company: "Doug Grant Plumbing & Heating",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "Plumbing & Heating Services, handy man services",
    tradeOrBusinessType: "Plumbing & Heating Services, handy man services",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["plumbing", "heating"],
    notes: "",
  },
  {
    id: "31",
    firstName: "Dougie",
    lastName: "Harrold",
    email: "Info@mayburylandscaping.co.uk",
    phone: "07899903374",
    company: "Maybury Landscaping",
    businessCategory: "Construction & Building",
    serviceDescription: "Driveways, Drainage, Landscaping",
    tradeOrBusinessType: "Driveways, Drainage, Landscaping",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["landscaping", "driveways"],
    notes: "",
  },
  {
    id: "32",
    firstName: "Dougie",
    lastName: "Hearn",
    email: "info@redwolfelectrical.co.uk",
    phone: "07743904602 ",
    company: "Red Wolf Electrical",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "Domestic and Commercial Electrical Installation and Maintenace",
    tradeOrBusinessType: "Domestic and Commercial Electrical Installation and Maintenace",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical"],
    notes: "",
  },
  {
    id: "33",
    firstName: "Euan",
    lastName: "Allan",
    email: "",
    phone: "0784954860",
    company: "Bumper to Bumper Garage",
    businessCategory: "Automotive",
    serviceDescription:
      "MOTs, servicing, fleet work, wheel alignment, clutches, tyres, exhausts, auto electricians and recovery.",
    tradeOrBusinessType:
      "MOTs, servicing, fleet work, wheel alignment, clutches, tyres, exhausts, auto electricians and recovery.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["automotive", "garage"],
    notes: "",
  },
  {
    id: "34",
    firstName: "Fiona",
    lastName: "White",
    email: "Whitecleaningservices28@gmail.com",
    phone: "07950884804",
    company: "White Cleaning Services",
    businessCategory: "Property, Cleaning & Maintenance",
    serviceDescription: "Domestic, commercial, builder cleans, sparkle cleans, pet/house sitting.",
    tradeOrBusinessType: "Domestic, commercial, builder cleans, sparkle cleans, pet/house sitting.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["cleaning"],
    notes: "",
  },
  {
    id: "35",
    firstName: "Fraser",
    lastName: "Campbell",
    email: "",
    phone: "",
    company: "",
    businessCategory: "",
    serviceDescription: "",
    tradeOrBusinessType: "",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: [],
    notes: "",
  },
  {
    id: "36",
    firstName: "Fraser",
    lastName: "Gordon",
    email: "gordonjopineryservices@outlook.com",
    phone: "07432501375",
    company: "Gordon Joinery Services",
    businessCategory: "Construction & Building",
    serviceDescription: "All aspects of Joinery",
    tradeOrBusinessType: "All aspects of Joinery",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery"],
    notes: "",
  },
  {
    id: "37",
    firstName: "Garry",
    lastName: "Lynch",
    email: "garry.lynch70@gmail.com",
    phone: "07879011860",
    company: "Bear Media",
    businessCategory: "Technology & Digital",
    serviceDescription:
      "Content Creation, Video Marketing & Drone Services, Content Creator, Photography, Video, Drone and Websites",
    tradeOrBusinessType:
      "Content Creation, Video Marketing & Drone Services, Content Creator, Photography, Video, Drone and Websites",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["media", "video", "photography"],
    notes: "",
  },
  {
    id: "38",
    firstName: "Gary",
    lastName: "Young",
    email: "gary@themindfulennterprise.org",
    phone: "07803584139",
    company: "The Mindful Enterprise",
    businessCategory: "Health & Wellbeing",
    serviceDescription: "Therapy, self development coaching, health retreats and mind mastery training.",
    tradeOrBusinessType: "Therapy, self development coaching, health retreats and mind mastery training.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["therapy", "coaching", "health"],
    notes: "",
  },
  {
    id: "39",
    firstName: "Graeme",
    lastName: "Ashton",
    email: "Graemeashton1@gmail.com",
    phone: "07903701194",
    company: "Graeme Ashton",
    businessCategory: "Other Services",
    serviceDescription: "Sales Coaching for Home improvement companies",
    tradeOrBusinessType: "Sales Coaching for Home improvement companies",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["coaching", "sales"],
    notes: "",
  },
  {
    id: "40",
    firstName: "Hamish",
    lastName: "Scanlan",
    email: "hamish@scgconsulting.uk",
    phone: "07551237777",
    company: "SCG Consulting",
    businessCategory: "Technology & Digital",
    serviceDescription: "Business telecomms & IT",
    tradeOrBusinessType: "Business telecomms & IT",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["telecoms", "it"],
    notes: "",
  },
  {
    id: "41",
    firstName: "Ian",
    lastName: "Hunt",
    email: "mail@ihc-arc.com",
    phone: "07968181222",
    company: "iHC Architecture Ltd",
    businessCategory: "Construction & Building",
    serviceDescription:
      "Full architectural services from initial sketch proposal to final inspections & everything inbetween. Planning application, building warrant, construction drawings, CML & self build certs. Domestic, residential, commercial & retail.",
    tradeOrBusinessType:
      "Full architectural services from initial sketch proposal to final inspections & everything inbetween. Planning application, building warrant, construction drawings, CML & self build certs. Domestic, residential, commercial & retail.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["architecture"],
    notes: "",
  },
  {
    id: "42",
    firstName: "Isabel",
    lastName: "Stobbie",
    email: "isabel@lsmarchitecture.co.uk",
    phone: "07828845354",
    company: "LSM Architecture",
    businessCategory: "Construction & Building",
    serviceDescription: "Architectural services",
    tradeOrBusinessType: "Architectural services",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["architecture"],
    notes: "",
  },
  {
    id: "43",
    firstName: "Jack",
    lastName: "Pearce",
    email: "jpelectricalsolutions4@gmail.com",
    phone: "07850487930",
    company: "JP Electrical Solutions",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All aspects of Electrical work",
    tradeOrBusinessType: "All aspects of Electrical work",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical"],
    notes: "",
  },
  {
    id: "44",
    firstName: "Jack",
    lastName: "Smith",
    email: "jack.smith@supremefinancialsolutions.co.uk",
    phone: "07581559775",
    company: "Supreme Financial Solutions ",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Life Insurance, Critical illness cover, income protectio, accident/injury cover, Key person over, shareholder protection & Relevant Life Cover",
    tradeOrBusinessType:
      "Life Insurance, Critical illness cover, income protectio, accident/injury cover, Key person over, shareholder protection & Relevant Life Cover",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["insurance", "financial-services"],
    notes: "",
  },
  {
    id: "45",
    firstName: "Jason",
    lastName: "Craig",
    email: "Jason@cnxrecruitment.co.uk",
    phone: "07586 393096",
    company: "CNX Recruitment",
    businessCategory: "Recruitment & HR",
    serviceDescription: "Blue & White collar construction recruitment",
    tradeOrBusinessType: "Blue & White collar construction recruitment",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["recruitment", "construction"],
    notes: "",
  },
  {
    id: "46",
    firstName: "Jay",
    lastName: "Fairgrieve",
    email: "jay@i-d-h.co.uk",
    phone: "07957649785",
    company: "IDH Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Luxury home builds, extensions & renovations, Trampoline parks.",
    tradeOrBusinessType: "Luxury home builds, extensions & renovations, Trampoline parks.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction", "luxury-homes"],
    notes: "",
  },
  {
    id: "47",
    firstName: "John",
    lastName: "Ross",
    email: "info@cleanteccleaningservices.co.uk",
    phone: "07970098519",
    company: "CleanTEC Ltd",
    businessCategory: "Property, Cleaning & Maintenance",
    serviceDescription:
      "Commercial, construction & residential cleaning. Executive travel. Run club, hyrox classes, online coaching.",
    tradeOrBusinessType:
      "Commercial, construction & residential cleaning. Executive travel. Run club, hyrox classes, online coaching.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["cleaning", "travel", "fitness"],
    notes: "",
  },
  {
    id: "48",
    firstName: "Jonathon",
    lastName: "Morrice",
    email: "admin@newtownrenovations.co.uk",
    phone: "07812768739",
    company: "Newtown Renovations Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "All joinery work, extensions,renovations, kitchens, bathrooms,sash & case window specialists.",
    tradeOrBusinessType:
      "All joinery work, extensions,renovations, kitchens, bathrooms,sash & case window specialists.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery", "renovations"],
    notes: "",
  },
  {
    id: "49",
    firstName: "Jonny",
    lastName: "Blurton",
    email: "jonny.blurton@orocco.co.uk",
    phone: "07969023304",
    company: "Terpex Group",
    businessCategory: "Construction & Building",
    serviceDescription: "Construction - all types.",
    tradeOrBusinessType: "Construction - all types.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction"],
    notes: "",
  },
  {
    id: "50",
    firstName: "Jordan",
    lastName: "Allan",
    email: "mastershieldroofing1@outlook.com",
    phone: "07719061039",
    company: "Mastershield Roofing & Property",
    businessCategory: "Construction & Building",
    serviceDescription:
      "Roofing services, traditional & modern roofing systems, leadwork, roughcasting, single ply, fibre glass roofing systems, repairs & full replacements.",
    tradeOrBusinessType:
      "Roofing services, traditional & modern roofing systems, leadwork, roughcasting, single ply, fibre glass roofing systems, repairs & full replacements.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["roofing"],
    notes: "",
  },
  {
    id: "51",
    firstName: "Jordan",
    lastName: "Stevenson",
    email: "js@stevensonstonemasonry.com",
    phone: "07938193129",
    company: "Stevenson Stonemasonry",
    businessCategory: "Construction & Building",
    serviceDescription: "Traditional Stonmasonry",
    tradeOrBusinessType: "Traditional Stonmasonry",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["stonemasonry"],
    notes: "",
  },
  {
    id: "52",
    firstName: "Josh",
    lastName: "Carson",
    email: "Josh@gearedapp.co.uk ",
    phone: "07896106625 ",
    company: "GearedApp",
    businessCategory: "Technology & Digital",
    serviceDescription: "Bespoke software development - web & mobile apps, websites, agile teams",
    tradeOrBusinessType: "Bespoke software development - web & mobile apps, websites, agile teams",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["software", "web-development"],
    notes: "",
  },
  {
    id: "53",
    firstName: "Kayleigh",
    lastName: "Johnstone",
    email: "sales@signmanembroidery.co.uk",
    phone: "07725840547",
    company: "Signman Embroidery",
    businessCategory: "Other Services",
    serviceDescription: "Embroidery & print service on clothing, workwear & accessories.",
    tradeOrBusinessType: "Embroidery & print service on clothing, workwear & accessories.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["embroidery", "print", "workwear"],
    notes: "",
  },
  {
    id: "54",
    firstName: "Kevin",
    lastName: "Crawford ",
    email: "K.Crawfordltd@outlook.com",
    phone: "07746534940",
    company: "K.Crawford Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Joinery",
    tradeOrBusinessType: "Joinery",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery"],
    notes: "",
  },
  {
    id: "55",
    firstName: "Kieran",
    lastName: "Falconer",
    email: "info@capital-plumbing.co.uk",
    phone: "07857834651",
    company: "Capital Plumbing",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All plumbing & heating works, bathrooms too.",
    tradeOrBusinessType: "All plumbing & heating works, bathrooms too.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["plumbing", "heating"],
    notes: "",
  },
  {
    id: "56",
    firstName: "Kirsty",
    lastName: "Allan",
    email: "kirsty@cityaccessscaffolding.co.uk",
    phone: "07812354172",
    company: "City Access Scaffolding",
    businessCategory: "Construction & Building",
    serviceDescription: "Scaffolding",
    tradeOrBusinessType: "Scaffolding",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["scaffolding"],
    notes: "",
  },
  {
    id: "57",
    firstName: "Kyle",
    lastName: "Marrins",
    email: "info@ferngardens.net",
    phone: "01315818401",
    company: "Fern Landscape Garden Company Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Landscaping & Garden Maintenance, gardening.",
    tradeOrBusinessType: "Landscaping & Garden Maintenance, gardening.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["landscaping", "gardening"],
    notes: "",
  },
  {
    id: "58",
    firstName: "Lewis",
    lastName: "Alexander",
    email: "Lewis@ladigitalmarketing.uk",
    phone: "07712447312",
    company: "LA Digital Marketing",
    businessCategory: "Technology & Digital",
    serviceDescription: "Lead Generation, Websites, SEO, Facebook / Instagram Paid Advertising",
    tradeOrBusinessType: "Lead Generation, Websites, SEO, Facebook / Instagram Paid Advertising",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["digital-marketing", "seo", "websites"],
    notes: "",
  },
  {
    id: "59",
    firstName: "Lewis",
    lastName: "Mitchell",
    email: "lewis.mitchell@wpa-hcp.org.uk",
    phone: "07947994471",
    company: "Shield Healthcare Solutions",
    businessCategory: "Finance & Legal",
    serviceDescription: "We sell Private Medical Insurance on behalf of WPA",
    tradeOrBusinessType: "We sell Private Medical Insurance on behalf of WPA",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["insurance", "healthcare"],
    notes: "",
  },
  {
    id: "60",
    firstName: "Liam",
    lastName: "Burke",
    email: "\nLiamburke@edinburghpowerclean.com",
    phone: "07931 782733",
    company: "The Edinburgh power clean company",
    businessCategory: "Property, Cleaning & Maintenance",
    serviceDescription: "Exterior Cleaning",
    tradeOrBusinessType: "Exterior Cleaning",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["cleaning"],
    notes: "",
  },
  {
    id: "61",
    firstName: "Lorraine",
    lastName: "Fairgrieve ",
    email: "lollyscards@sky.com",
    phone: "07873130284",
    company: "Lollys Cards & Creations",
    businessCategory: "Other Services",
    serviceDescription: "Personalised items such as mugs, adult/child clothing & workwear.",
    tradeOrBusinessType: "Personalised items such as mugs, adult/child clothing & workwear.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["gifts", "personalisation"],
    notes: "",
  },
  {
    id: "62",
    firstName: "Lynsay",
    lastName: "Acamovic",
    email: "Lynsay@mortgageit.co.uk",
    phone: "07535971204",
    company: "MortgageIt Ltd",
    businessCategory: "Finance & Legal",
    serviceDescription: "Mortgage and Insurance Protection",
    tradeOrBusinessType: "Mortgage and Insurance Protection",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["mortgages", "insurance"],
    notes: "",
  },
  {
    id: "63",
    firstName: "Marc",
    lastName: "Faughnan",
    email: "marc@blackmoonlighting.com",
    phone: "07815 823 771",
    company: "Blackmoon Lighting",
    businessCategory: "Construction & Building",
    serviceDescription:
      "Lighting Design, Supply and Control (Commercial & Residential) Home Automation, Home Cinema, Audiovisual",
    tradeOrBusinessType:
      "Lighting Design, Supply and Control (Commercial & Residential) Home Automation, Home Cinema, Audiovisual",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["lighting", "home-automation"],
    notes: "",
  },
  {
    id: "64",
    firstName: "Mark",
    lastName: "Blair",
    email: "mark@effectivenow.co.uk",
    phone: "07825686971",
    company: "Effectivenow Ltd",
    businessCategory: "Other Services",
    serviceDescription: "Business support & team developement, Business partnership programme.",
    tradeOrBusinessType: "Business support & team developement, Business partnership programme.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["business-support", "coaching"],
    notes: "",
  },
  {
    id: "65",
    firstName: "Mark",
    lastName: "Donoghue",
    email: "info@heatplusscotland.co.uk",
    phone: "07889496777",
    company: "Heatplus Scotland",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "Plumbing & Heating",
    tradeOrBusinessType: "Plumbing & Heating",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["plumbing", "heating"],
    notes: "",
  },
  {
    id: "66",
    firstName: "Mark",
    lastName: "McKenzie",
    email: "mark.mcKenzie@wpa-hcp.org.uk",
    phone: "07793726457",
    company: "Shield Healthcare Solutions",
    businessCategory: "Finance & Legal",
    serviceDescription: "We sell Private Medical Insurance on behalf of WPA",
    tradeOrBusinessType: "We sell Private Medical Insurance on behalf of WPA",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["insurance", "healthcare"],
    notes: "",
  },
  {
    id: "67",
    firstName: "Matthew",
    lastName: "Currie",
    email: "info@roxelectrical.co.uk",
    phone: "07983675377",
    company: "Rox Electrical",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All types of domestic & commercial electrical work.",
    tradeOrBusinessType: "All types of domestic & commercial electrical work.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical"],
    notes: "",
  },
  {
    id: "68",
    firstName: "Matthew",
    lastName: "Wright",
    email: "",
    phone: "07912341262",
    company: "Blackmoon Lighting",
    businessCategory: "Construction & Building",
    serviceDescription:
      "Lighting supplier & design including controls for various systems. Main contractor, mainly interior fitout. Supply all trades, temp labour solutions & site managers.",
    tradeOrBusinessType:
      "Lighting supplier & design including controls for various systems. Main contractor, mainly interior fitout. Supply all trades, temp labour solutions & site managers.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["lighting", "fitout"],
    notes: "",
  },
  {
    id: "69",
    firstName: "Michael",
    lastName: "Daniel",
    email: "michael@sawmill-contracts.co.uk",
    phone: "07888007460",
    company: "Castleview Group",
    businessCategory: "Construction & Building",
    serviceDescription: "Construction, Building, Joinery, Plumbing & Heating",
    tradeOrBusinessType: "Construction, Building, Joinery, Plumbing & Heating",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction", "building"],
    notes: "",
  },
  {
    id: "70",
    firstName: "Michael",
    lastName: "Glasgow",
    email: "info@loftboardingcompany.com",
    phone: "07515426631",
    company: "The Loft Boarding Company Limited",
    businessCategory: "Construction & Building",
    serviceDescription: "Loft storage/ Lights/ Ladders & Insulation.",
    tradeOrBusinessType: "Loft storage/ Lights/ Ladders & Insulation.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["loft-conversion", "storage"],
    notes: "",
  },
  {
    id: "71",
    firstName: "Michelle",
    lastName: "Allan",
    email: "Info@theembroideryshop.co.uk",
    phone: "07809 121106",
    company: "The Embroidery Shop",
    businessCategory: "Other Services",
    serviceDescription: "Supplying workwear and uniforms and merchandise for Embroidery & Printing of company logos",
    tradeOrBusinessType: "Supplying workwear and uniforms and merchandise for Embroidery & Printing of company logos",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["embroidery", "workwear"],
    notes: "",
  },
  {
    id: "72",
    firstName: "Mike",
    lastName: "Scott",
    email: "info@mdssecuritysystems.co.uk",
    phone: "07763584517",
    company: "MDS Security Systems",
    businessCategory: "Technology & Digital",
    serviceDescription:
      "Installation & maintainance of intruder, fire alarms, CCTV, access control, intercoms, lighting, data & wifi.",
    tradeOrBusinessType:
      "Installation & maintainance of intruder, fire alarms, CCTV, access control, intercoms, lighting, data & wifi.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["security", "cctv"],
    notes: "",
  },
  {
    id: "73",
    firstName: "Mikey",
    lastName: "Riley",
    email: "info@mrelimited.co.uk",
    phone: "07717357707",
    company: "M R Electrical Ltd",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All trades, gas, electrical, plumbing, maintenance & cleaning.",
    tradeOrBusinessType: "All trades, gas, electrical, plumbing, maintenance & cleaning.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical", "plumbing", "maintenance"],
    notes: "",
  },
  {
    id: "74",
    firstName: "Nathan",
    lastName: "Ross",
    email: "nathan@breadalbanefinance.co.uk",
    phone: "07367211853",
    company: "Breadalbane Finance ",
    businessCategory: "Finance & Legal",
    serviceDescription: "Asset Invoice, Unsecured Business loans, commercial mortages and development finance",
    tradeOrBusinessType: "Asset Invoice, Unsecured Business loans, commercial mortages and development finance",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["finance", "mortgages"],
    notes: "",
  },
  {
    id: "75",
    firstName: "Nicola",
    lastName: "Hancock",
    email: "nicky@nicola-hancock.co.uk",
    phone: "07990578095",
    company: "Nicola Hancock Chartered Accountant",
    businessCategory: "Finance & Legal",
    serviceDescription: "Year end accounts, corporate & personal tax, VAT, business start ups, payroll services.",
    tradeOrBusinessType: "Year end accounts, corporate & personal tax, VAT, business start ups, payroll services.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["accounting", "tax"],
    notes: "",
  },
  {
    id: "76",
    firstName: "Paul",
    lastName: "Bestford ",
    email: "Paul@mwassociates.net",
    phone: "07841 521514",
    company: "Melrose Wemyss Associates",
    businessCategory: "Finance & Legal",
    serviceDescription: "Mortgages / Protection / Business Protection / Pensions & Investment / General Insurance ",
    tradeOrBusinessType: "Mortgages / Protection / Business Protection / Pensions & Investment / General Insurance ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["mortgages", "insurance", "pensions"],
    notes: "",
  },
  {
    id: "77",
    firstName: "Paul",
    lastName: "Demarco",
    email: "mrgleam@hotmail.com",
    phone: "07455002559",
    company: "Gleam Machine Valeting",
    businessCategory: "Other Services",
    serviceDescription:
      "Car wash, mobile valeting, machine polish, ceramic coating, minor scratch removal. Commercial & domestic removals, house/office clearnce, waste clearances, storage facilities, Deliveries & collections, man with van.",
    tradeOrBusinessType:
      "Car wash, mobile valeting, machine polish, ceramic coating, minor scratch removal. Commercial & domestic removals, house/office clearnce, waste clearances, storage facilities, Deliveries & collections, man with van.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["valeting", "removals"],
    notes: "",
  },
  {
    id: "78",
    firstName: "Paul",
    lastName: "Marko",
    email: "pmarkojoiner@outlook.com",
    phone: "07718998225",
    company: "Marko & Linton Joinery & Building Services Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Service provided all contractor.",
    tradeOrBusinessType: "Service provided all contractor.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery", "building"],
    notes: "",
  },
  {
    id: "79",
    firstName: "Paul",
    lastName: "Mclung",
    email: "info@pmcfabricationandwelding.com",
    phone: "07713185932",
    company: "PMC Fabricating & Welding",
    businessCategory: "Construction & Building",
    serviceDescription: "Blacksmith & Fabricating Bespoke gates, railings and all forms of welding ",
    tradeOrBusinessType: "Blacksmith & Fabricating Bespoke gates, railings and all forms of welding ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["fabrication", "welding"],
    notes: "",
  },
  {
    id: "80",
    firstName: "Peter",
    lastName: "Finlay",
    email: "gasspecwork@gmail.com",
    phone: "07956074501",
    company: "Gas Spec ( Heating & Plumbing )",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "Domestic, commerc ial, LPG & commercial catering work.",
    tradeOrBusinessType: "Domestic, commerc ial, LPG & commercial catering work.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["gas", "plumbing", "heating"],
    notes: "",
  },
  {
    id: "81",
    firstName: "Rene",
    lastName: "Laidlaw",
    email: "",
    phone: "07595158522",
    company: "",
    businessCategory: "",
    serviceDescription: "",
    tradeOrBusinessType: "",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: [],
    notes: "",
  },
  {
    id: "82",
    firstName: "Robert",
    lastName: "Wilson",
    email: "robert.wilson@gensource.co.uk",
    phone: "07534811897",
    company: "Gensource",
    businessCategory: "Other Services",
    serviceDescription: "Sustainable energy services",
    tradeOrBusinessType: "Sustainable energy services",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["energy", "sustainability"],
    notes: "",
  },
  {
    id: "83",
    firstName: "Robyn",
    lastName: "Shepherd",
    email: "Robyn@forthscaffolding.co.uk",
    phone: "07450590660",
    company: "Forth Scaffolding Ltd",
    businessCategory: "Construction & Building",
    serviceDescription:
      "Scaffolding erection and dismantle for all domestic, commercial & industrial clients.Local community public house. Live music and events. Food",
    tradeOrBusinessType:
      "Scaffolding erection and dismantle for all domestic, commercial & industrial clients.Local community public house. Live music and events. Food",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["scaffolding", "hospitality"],
    notes: "",
  },
  {
    id: "84",
    firstName: "Rory",
    lastName: "Boyd",
    email: "Mrbpropertyinvestmentsltd@gmail.com",
    phone: "07497241119",
    company: "MRB Properties ltd & Boyd Financial Solutions Ltd",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Commercial Finance Broker , Property , Business, Asset and Car Finance . / Hands off Property Portfolio builder ",
    tradeOrBusinessType:
      "Commercial Finance Broker , Property , Business, Asset and Car Finance . / Hands off Property Portfolio builder ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["finance", "property"],
    notes: "",
  },
  {
    id: "85",
    firstName: "Ryan",
    lastName: "Evans",
    email: "info@castletrees.co.uk",
    phone: "07590012448",
    company: "Castle Trees",
    businessCategory: "Construction & Building",
    serviceDescription: "Tree surgery,/removals, stump grinding, area clearance & hedgework.",
    tradeOrBusinessType: "Tree surgery,/removals, stump grinding, area clearance & hedgework.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["tree-surgery", "landscaping"],
    notes: "",
  },
  {
    id: "86",
    firstName: "Ryan",
    lastName: "Lumsden",
    email: "RLE2026@outlook.com",
    phone: "07814263931",
    company: "R.Lumsden Electrical Ltd",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "Electrician",
    tradeOrBusinessType: "Electrician",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["electrical"],
    notes: "",
  },
  {
    id: "87",
    firstName: "Ryan",
    lastName: "Oconner",
    email: "ryan@performscalemarketing.com",
    phone: "07950278084",
    company: "Perform & Scale",
    businessCategory: "Technology & Digital",
    serviceDescription: "Lead generation for home improvement businesses",
    tradeOrBusinessType: "Lead generation for home improvement businesses",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["marketing", "lead-generation"],
    notes: "",
  },
  {
    id: "88",
    firstName: "Sam",
    lastName: "Stuart",
    email: "",
    phone: "078725213638",
    company: "Hard Graft Garden Services Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "All aspects of gardening & landscaping.",
    tradeOrBusinessType: "All aspects of gardening & landscaping.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["gardening", "landscaping"],
    notes: "",
  },
  {
    id: "89",
    firstName: "Scott",
    lastName: "Houston",
    email: "Scott@cnxrecruitment.co.uk ",
    phone: "07960908144",
    company: "CNX Recruitment",
    businessCategory: "Recruitment & HR",
    serviceDescription: "Blue & White collar construction recruitment",
    tradeOrBusinessType: "Blue & White collar construction recruitment",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["recruitment", "construction"],
    notes: "",
  },
  {
    id: "90",
    firstName: "Sedrik",
    lastName: "Craigen ",
    email: "Sedrik@newlinemicrocement.co.uk",
    phone: "07752429022",
    company: "NewLine Microcement Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Terrazzo & Microcement, Seamless decorative surface specialist",
    tradeOrBusinessType: "Terrazzo & Microcement, Seamless decorative surface specialist",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["flooring", "decorative-surfaces"],
    notes: "",
  },
  {
    id: "91",
    firstName: "Shaun",
    lastName: "Dunn",
    email: "",
    phone: "07453285843",
    company: "SD Plumbing & Heating",
    businessCategory: "Electrical, Gas & Renewables",
    serviceDescription: "All aspects of plumbing & heating, kitchens, bathrooms & renovations.",
    tradeOrBusinessType: "All aspects of plumbing & heating, kitchens, bathrooms & renovations.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["plumbing", "heating"],
    notes: "",
  },
  {
    id: "92",
    firstName: "Steven",
    lastName: "Campbell",
    email: "sjcjoinery@mail.com",
    phone: "07598253512",
    company: "SJC Joinery",
    businessCategory: "Construction & Building",
    serviceDescription: "High end bespoke joinery, custom kitchens & bedroom furniture.",
    tradeOrBusinessType: "High end bespoke joinery, custom kitchens & bedroom furniture.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["joinery", "kitchens", "bespoke"],
    notes: "",
  },
  {
    id: "93",
    firstName: "Steven",
    lastName: "Guthrie",
    email: "steven.guthrie@sjpp.co.uk",
    phone: "07470245345",
    company: "Guthrie Wealth Consultancy",
    businessCategory: "Finance & Legal",
    serviceDescription:
      "Financial planning, pensions, investments, life & business protection. Tax mitigation, maximising income for clients.",
    tradeOrBusinessType:
      "Financial planning, pensions, investments, life & business protection. Tax mitigation, maximising income for clients.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["financial-planning", "pensions", "investments"],
    notes: "",
  },
  {
    id: "94",
    firstName: "Steven",
    lastName: "McCole",
    email: "slickbuildingservices@gmail.com",
    phone: "07862622947",
    company: "Slick Building Services",
    businessCategory: "Construction & Building",
    serviceDescription: "Extensions, garden transformations, renovations, brick & block work, joinery work.",
    tradeOrBusinessType: "Extensions, garden transformations, renovations, brick & block work, joinery work.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["building", "extensions", "renovations"],
    notes: "",
  },
  {
    id: "95",
    firstName: "Steven",
    lastName: "Mitchell",
    email: "steven@scotiapropertyprojects.co.uk",
    phone: "07889208709",
    company: "Scotia Property Projects Ltd",
    businessCategory: "Construction & Building",
    serviceDescription: "Building, services, extensions, conversions, renovations.",
    tradeOrBusinessType: "Building, services, extensions, conversions, renovations.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["building", "conversions", "renovations"],
    notes: "",
  },
  {
    id: "96",
    firstName: "Steven",
    lastName: "Summone",
    email: "steven.summone@gmail.com ",
    phone: "07973 502 311",
    company: "Summone Consulting",
    businessCategory: "Technology & Digital",
    serviceDescription:
      "AI & Cloud Productivity Consultant – I help businesses work smarter, not harder, by leveraging AI, Microsoft 365, and automation to save time, increase productivity, and gain a competitive edge.",
    tradeOrBusinessType:
      "AI & Cloud Productivity Consultant – I help businesses work smarter, not harder, by leveraging AI, Microsoft 365, and automation to save time, increase productivity, and gain a competitive edge.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["ai", "consulting", "cloud"],
    notes: "",
  },
  {
    id: "97",
    firstName: "Stuart",
    lastName: "Brown",
    email: "tyninghamesawmill@gmail.com",
    phone: "07977036178",
    company: "Tyninghame Sawmill",
    businessCategory: "Construction & Building",
    serviceDescription: "Sawn timber,larch cladding, sleepers & fencing, dried firewood & logs. ",
    tradeOrBusinessType: "Sawn timber,larch cladding, sleepers & fencing, dried firewood & logs. ",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["timber", "sawmill"],
    notes: "",
  },
  {
    id: "98",
    firstName: "Suzanne",
    lastName: "Boyle",
    email: "suzanne.boyle@travelcounsellors.com",
    phone: "01975592851",
    company: "Suzanne Boyle - Travel Counsellor",
    businessCategory: "Other Services",
    serviceDescription: "Travel Agent offering bespoke, tailored travel for busy professionals",
    tradeOrBusinessType: "Travel Agent offering bespoke, tailored travel for busy professionals",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["travel"],
    notes: "",
  },
  {
    id: "99",
    firstName: "Tony",
    lastName: "Di Lorenzo",
    email: "tony.dilorenzo@decco.co.uk",
    phone: "07827962791",
    company: "Bell Donaldson Steele",
    businessCategory: "Construction & Building",
    serviceDescription: "Supply of construction fixings, ironmongory, site supplies, powertools & metalwork.",
    tradeOrBusinessType: "Supply of construction fixings, ironmongory, site supplies, powertools & metalwork.",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["construction-supplies", "tools"],
    notes: "",
  },
  {
    id: "100",
    firstName: "Yvonne",
    lastName: "Bell",
    email: "yw.lvbs@yahoo.co.uk",
    phone: "",
    company: "Little Voices Big Stars",
    businessCategory: "Other Services",
    serviceDescription:
      "Modern singing classes in Midlothian. Helping children and adults grow in confidence through singing",
    tradeOrBusinessType:
      "Modern singing classes in Midlothian. Helping children and adults grow in confidence through singing",
    role: "Member",
    location: "Edinburgh",
    membershipType: "Member",
    status: "active",
    joinDate: "2024-09-01",
    renewalDate: "2025-09-01",
    eventsAttended: 0,
    tags: ["singing", "education"],
    notes: "",
  },
]

export function initStorage() {
  if (typeof window === "undefined") return

  const existingMembers = localStorage.getItem(STORAGE_KEYS.MEMBERS)
  const existingEvents = localStorage.getItem(STORAGE_KEYS.EVENTS)

  if (!existingMembers) {
    localStorage.setItem(STORAGE_KEYS.MEMBERS, JSON.stringify(DEMO_MEMBERS))
    console.log(`[v0] ✅ Loaded ${DEMO_MEMBERS.length} members into localStorage`)

    // Count unique trades
    const uniqueTrades = new Set(DEMO_MEMBERS.map((m) => m.tradeOrBusinessType).filter(Boolean))
    console.log(`[v0] ✅ Detected ${uniqueTrades.size} unique trades`)
  } else {
    const members = JSON.parse(existingMembers)
    console.log(`[v0] ℹ️ Found existing ${members.length} members in localStorage`)
  }

  if (!existingEvents) {
    localStorage.setItem(STORAGE_KEYS.EVENTS, JSON.stringify([]))
  }
}

// Members CRUD
export function getMembers(): Member[] {
  if (typeof window === "undefined") return []
  const data = localStorage.getItem(STORAGE_KEYS.MEMBERS)
  return data ? JSON.parse(data) : []
}

export function getMemberById(id: string): Member | null {
  const members = getMembers()
  return members.find((m) => m.id === id) || null
}

export function saveMembers(members: Member[]) {
  if (typeof window === "undefined") return
  localStorage.setItem(STORAGE_KEYS.MEMBERS, JSON.stringify(members))
}

export function deleteMember(id: string) {
  const members = getMembers().filter((m) => m.id !== id)
  localStorage.setItem(STORAGE_KEYS.MEMBERS, JSON.stringify(members))
}

// Events CRUD
export function getEvents(): Event[] {
  if (typeof window === "undefined") return []
  const data = localStorage.getItem(STORAGE_KEYS.EVENTS)
  return data ? JSON.parse(data) : []
}

export function saveEvent(event: Event) {
  const events = getEvents()
  const existingIndex = events.findIndex((e) => e.id === event.id)

  if (existingIndex >= 0) {
    events[existingIndex] = event
  } else {
    events.push(event)
  }

  saveEvents(events)
}

export function saveEvents(events: Event[]) {
  if (typeof window === "undefined") return
  localStorage.setItem(STORAGE_KEYS.EVENTS, JSON.stringify(events))
}

export function deleteEvent(id: string) {
  const events = getEvents().filter((e) => e.id !== id)
  saveEvents(events)
}

// Utility functions
export function resetAppData() {
  if (typeof window === "undefined") return
  localStorage.setItem(STORAGE_KEYS.MEMBERS, JSON.stringify(DEMO_MEMBERS))
  localStorage.setItem(STORAGE_KEYS.EVENTS, JSON.stringify([]))
}

export function generateId() {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
}
